package com.lanhuayan.petstore.entity;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.petId
     *
     * @mbg.generated
     */
    private Integer petid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipDate
     *
     * @mbg.generated
     */
    private Date shipdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.OrderStatus
     *
     * @mbg.generated
     */
    private String orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.complete
     *
     * @mbg.generated
     */
    private byte[] complete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.petId
     *
     * @return the value of order.petId
     *
     * @mbg.generated
     */
    public Integer getPetid() {
        return petid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.petId
     *
     * @param petid the value for order.petId
     *
     * @mbg.generated
     */
    public void setPetid(Integer petid) {
        this.petid = petid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.quantity
     *
     * @return the value of order.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.quantity
     *
     * @param quantity the value for order.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipDate
     *
     * @return the value of order.shipDate
     *
     * @mbg.generated
     */
    public Date getShipdate() {
        return shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipDate
     *
     * @param shipdate the value for order.shipDate
     *
     * @mbg.generated
     */
    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.OrderStatus
     *
     * @return the value of order.OrderStatus
     *
     * @mbg.generated
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.OrderStatus
     *
     * @param orderstatus the value for order.OrderStatus
     *
     * @mbg.generated
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.complete
     *
     * @return the value of order.complete
     *
     * @mbg.generated
     */
    public byte[] getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.complete
     *
     * @param complete the value for order.complete
     *
     * @mbg.generated
     */
    public void setComplete(byte[] complete) {
        this.complete = complete;
    }
}