package com.lanhuayan.petstore.dao;

import com.lanhuayan.petstore.entity.Apiresponse;
import java.util.List;

public interface ApiresponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apiresponse
     *
     * @mbg.generated
     */
    int insert(Apiresponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apiresponse
     *
     * @mbg.generated
     */
    List<Apiresponse> selectAll();
}